"""Security incident report generation module."""

from datetime import datetime, timezone
from pathlib import Path
from tankdozer.utils.display import header, success, info, kv, divider


def _banner():
    return r"""
█▀▄▀█ ▄▄█ █▄ ▄█ ██▄ ▄▀▄ █▀▄ ███ █ █ ██▀ █ ▄▀▄
█░▀░█ ░░░█ █░▀░█ █▄█ █░█ █░█ █░███▄█ █▄▄ █ █░█
══════════════════════════════════════════════════════════
          TANK & DOZER INCIDENT RESPONSE REPORT
     Cybersecurity Incident Response Framework v1.0
══════════════════════════════════════════════════════════"""


def run_report(args):
    command = args.command
    header(f"Report Generation: {command}", "info")

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    report = _banner()
    report += f"\n\nGenerated: {now}\n"

    if command == "generate":
        report += """
────────────────────────────────────────────────────────
INCIDENT RESPONSE REPORT
────────────────────────────────────────────────────────

1. EXECUTIVE SUMMARY
   A comprehensive security incident analysis has been
   performed across monitored assets. The following report
   outlines findings, response actions, and recommendations.

2. FINDINGS SUMMARY
   ┌─────────────────────┬─────────────────────────────┐
   │ Category            │ Count                       │
   ├─────────────────────┼─────────────────────────────┤
   │ Critical            │ 0                           │
   │ High                │ 1                           │
   │ Medium              │ 3                           │
   │ Low                 │ 5                           │
   └─────────────────────┴─────────────────────────────┘

3. TIMELINE OF EVENTS
   • 2024-11-12 03:14  — Unusual outbound traffic detected
   • 2024-11-12 03:22  — IDS alert: port scan from 10.0.1.50
   • 2024-11-12 03:45  — Auth failure spike on ssh service
   • 2024-11-12 04:00  — Incident declared (severity: medium)

4. AFFECTED ASSETS
   • web-01.prod.example.com (10.0.1.50)
   • db-master.internal (10.0.2.10)

5. RESPONSE ACTIONS
   ✓ Blocked source IP at perimeter firewall
   ✓ Rotated compromised service credentials
   ✓ Initiated forensic imaging of affected hosts
   ✓ Deployed additional monitoring rules

6. RECOMMENDATIONS
   • Implement MFA for all administrative access
   • Deploy network segmentation for critical assets
   • Schedule quarterly tabletop exercises
   • Update incident response playbooks
"""
        info("Full incident report generated.")
        kv("Severity", "MEDIUM")
        kv("Status", "RESOLVED")

    elif command == "executive":
        report += """
────────────────────────────────────────────────────────
EXECUTIVE SUMMARY REPORT
────────────────────────────────────────────────────────

INCIDENT OVERVIEW
  A targeted reconnaissance campaign was identified and
  contained. No data exfiltration occurred. All affected
  assets have been remediated.

KEY METRICS
  • Time to detect: 45 minutes
  • Time to contain: 2 hours
  • Time to eradicate: 4 hours
  • Time to recover: 6 hours

BUSINESS IMPACT
  • No data loss
  • Minimal service disruption (< 30 minutes downtime)
  • No regulatory notification required

BUDGET IMPACT
  • Overtime: $12,500
  • Forensic analysis: $8,000
  • Additional tooling: $5,000
  • Total: $25,500

FOLLOW-UP ACTIONS
  1. Security awareness training — Q1 next quarter
  2. Deploy EDR solution — next month
  3. Third-party penetration test — next quarter
"""
        success("Executive summary generated.")

    elif command == "timeline":
        report += """
────────────────────────────────────────────────────────
INCIDENT TIMELINE REPORT
────────────────────────────────────────────────────────

Date: 2024-11-12

TIME (UTC)   | EVENT                               | SOURCE
─────────────┼─────────────────────────────────────┼──────────
03:12:45     | Scanner detected on network          | IDS-01
03:14:22     | C2 beacon outbound (185.130.5.x)    | FW-02
03:22:18     | Port sweep /24 subnet               | IDS-01
03:30:00     | Brute force on web-01 (ssh)         | AUTH-LOG
03:35:41     | Lateral movement to db-master       | EDR-01
03:45:00     | SOC notified of auth failure spike   | SIEM
03:50:00     | Incident declared (IR lead assigned) | MANUAL
04:00:00     | Source IP blocked at perimeter       | FW-01
04:15:00     | Credentials rotated on all affected  | MANUAL
05:30:00     | Forensic images acquired             | IR-TEAM
08:00:00     | Eradication confirmed                | IR-TEAM
10:00:00     | Systems restored to production       | OPS
"""
        info("Incident timeline generated.")

    report += f"\n{'─' * 54}\nReport generated by Tank & Dozer IR Framework\n"
    report_path = Path() / f"tankdozer_report_{command}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
    report_path.write_text(report)
    kv("Report Saved", str(report_path))
    print(f"\n{report}")
